### ISSUE TITLE
ztoml parsing error

### ISSUE THREAD

**Issue by funnotbun** [shepherdjerred/discord-plays-pokemon#95]
I filled in all my credentials on the config and it's throwing errors on a part of the file I did not touch
```console
$ npm run start

> @discord-plays-pokemon/monorepo@1.0.0 start
> npx tsx packages/backend/src/index.ts

error: Your configuration at /home/runner/discord-plays-pokemon/config.toml _is_ valid TOML, but it is not a valid configuration for this application.
The following problems were found:

 {"0":{"code":"invalid_type","expected":"object","message":"Expected object, received array","path":["game","browser","preferences"],"received":"array"}}` 
 ```

**Comment by shepherdjerred** [comment]
Thanks for reporting this! I'll take a look tomorrow.

Could you paste your config, with any credentials redacted

**Comment by shepherdjerred** [comment]
Fixed in 95403c39880437a9ea3a9aff419e4d9da76d12df

**Comment by funnotbun** [comment]
Oh! Sorry, I hadn't seen the reply
Thank you for your work!

**Comment by shepherdjerred** [comment]
No worries!

If you're trying the project out, you might want to stick to https://github.com/shepherdjerred/discord-plays-pokemon/commit/205959620f6d8e3788a54e4883a389716a185331 for a little. I'm making some bigger changes on `main` right now.
